name: Build

# Указываем, когда будет запускаться workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    # Указываем систему, на который будем билдить проект
    runs-on: ubuntu-latest

    # Клонируем репозиторий
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Build Project
        run: |
          g++ -o myapp main.cpp

      - name: Archive Artifact
        run: |
          zip -r .artifacts/myapp.zip myapp

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp.zip
          path: .artifacts/myapp.zip
