name: Build

# Указываем, когда будет запускаться workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    # Указываем систему, на который будем билдить проект
    runs-on: ubuntu-latest

    # Клонируем репозиторий
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Build Project
        run: |
          g++ -o myapp main.cpp

      - name: Archive Artifacts
        run: |
          zip -r artifacts.zip myapp
          mv artifacts.zip $GITHUB_WORKSPACE

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: myapp-artifact
          path: ${{ github.workspace }}/artifacts.zip
