name: Build

# Указываем, когда будет запускаться workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    # Указываем систему, на который будем билдить проект
    runs-on: ubuntu-latest

    # Клонируем репозиторий
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Build Project
        run: |
          g++ -o myapp main.cpp

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master

      - name: Archive Artifact
        run: |
          zip -r myapp.zip myapp

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp.zip
          path: myapp.zip

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: myapp.zip
          path: artifacts

      - name: Install curl
        run: sudo apt-get install -y curl

      - name: Print directory
        run: |
          pwd
          ls -la

      - name: Send File to Telegram
        run: |
          curl -F document=@"$PWD/myapp.zip" https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}
          