name: Build

# Указываем, когда будет запускаться workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    # Указываем систему, на который будем билдить проект
    runs-on: ubuntu-latest

    # Клонируем репозиторий
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Build Project
        run: |
          g++ -o myapp main.cpp

      - run: mkdir -p path/to/artifacts


      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp
          path: path/to/artifact/myapp