name: Build

# Указываем, когда будет запускаться workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    # Указываем систему, на который будем билдить проект
    runs-on: ubuntu-latest

    # Клонируем репозиторий
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Build Project
        run: |
          g++ -o myapp main.cpp

      - name: Install ghr
        run: |
          sudo apt-get -y install golang-github-tcnksm-ghr

      - name: Upload Artifacts
        uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GHR_PATH: artifacts/
          GHR_REPLACE: true
          GHR_COMPRESS: zip

