name: Build

# Указываем, когда будет запускаться workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    # Указываем систему, на который будем билдить проект
    runs-on: ubuntu-latest

    # Клонируем репозиторий
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Build Project
        run: |
          g++ -o simple_calculator main.cpp

      - name: Archive Artifact
        run: |
          zip -r simple_calculator.zip simple_calculator

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: simple_calculator.zi
          path: simple_calculator.zi
  
  analyse_code:
    # Указываем систему, на который будем билдить проект
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master

  docker_application:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest

          
  send_to_telgram:
    runs-on: ubuntu-latest
    
    steps:    

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Project
        run: |
          g++ -o simple_calculator main.cpp

      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
            to: ${{ secrets.TELEGRAM_CHAT_ID }}
            token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
            message: Uploaded artifacts
            document: simple_calculator


  windows_tg:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install g++
        run: choco install mingw -y

      - name: Build C++ Application
        run: g++ main.cpp -o simple_calculator.exe

      - name: Archive C++ Application
        run: |
          7z a myapp.zip myapp.exe

      - name: Send Application to Telegram
        uses: appleboy/telegram-action@master
        with:
            to: ${{ secrets.TELEGRAM_CHAT_ID }}
            token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
            message: Uploaded artifacts
            document: simple_calculator.exe
