name: Build

# Указываем, когда будет запускаться workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Build with Clang
        run: |
          clang++ main.cpp -o calculator.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: calculator.exe
          path: bin/Release/calculator.exe

          
  send_to_telgram:
    runs-on: ubuntu-latest
    
    steps:    

      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: calculator.exe

      - name: Print directory
        run: |
          ls -la

      - name: Archive C++ Application
        run: |
          7z a calculator.7z calculator.exe

      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
            to: ${{ secrets.TELEGRAM_CHAT_ID }}
            token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
            message: Windows & Linux versions
            document: calculator.7z


    
